from typing import Dict, Any, List

CURATED_THEMES: List[Dict[str, Any]] = [
    {
        "id": "wage",
        "icon": "🏢",
        "title": "임금체불 및 퇴직금 미지급",
        "subtitle": "외국인 근로자·취약계층 급여 및 퇴직금 보호",
        "case_name": "근로기준법위반·근로자퇴직급여보장법위반",
        "case_no": "2025다214123",
        "court_name": "대법원",
        "judgment_date": "2026.03.12",
        "official_url": "https://www.law.go.kr/LSW/precInfoP.do?precSeq=618511",
        "fact_summary": "사업주가 폐업을 이유로 외국인 근로자 및 일용직 노동자의 3개월 임금과 퇴직금을 지급하지 않고 회피한 사건",
        "court_holding": "근로자의 국적이나 체류 자격과 무관하게 실제 제공한 노동에 대한 임금 및 퇴직금은 최우선 변제 대상이며 사업주의 형사책임 인정",
        "remedy_guide": "고용노동부 진정 제기 및 로펌 프로보노 센터를 통한 대지급금(소액체당금) 신속 청구 가능",
        "image_url": "/static/images/news_wage.jpg"
    },
    {
        "id": "accident",
        "icon": "⚠️",
        "title": "산업재해(산재) 및 치료비",
        "subtitle": "현장 사고 치료비·휴업급여 및 유족보상 지원",
        "case_name": "요양불승인처분취소",
        "case_no": "2024두39189",
        "court_name": "대법원",
        "judgment_date": "2026.03.12",
        "official_url": "https://www.law.go.kr/LSW/precInfoP.do?precSeq=618535",
        "fact_summary": "건설 현장 및 제조업 작업 중 발생한 추락·기계 협착 사고에 대해 사업주가 안전조치를 소홀히 하여 근로자가 중상을 입은 사건",
        "court_holding": "사업주의 산업안전보건 기준 준수 의무 위반이 인정되며, 근로복지공단은 산재 요양 및 휴업급여를 전액 승인하여야 함",
        "remedy_guide": "산재 불승인 시 행정소송 및 사업주 대상 초과 민사 손해배상(위자료) 청구 지원",
        "image_url": "/static/images/news_accident.jpg"
    },
    {
        "id": "dismissal",
        "icon": "🚫",
        "title": "부당해고 및 직장 내 괴롭힘",
        "subtitle": "일방적 구두 해고·폭언에 대한 복직 및 위자료",
        "case_name": "부당해고구제재심판정취소",
        "case_no": "2023두54914",
        "court_name": "대법원",
        "judgment_date": "2026.01.29",
        "official_url": "https://www.law.go.kr/LSW/precInfoP.do?precSeq=616245",
        "fact_summary": "사업주가 서면 통지 없이 카카오톡이나 구두로 당일 해고를 통보하고, 상사의 지속적인 폭언과 따돌림이 있었던 사건",
        "court_holding": "근로기준법 제27조의 해고사유 서면통지 위반은 무조건 무효이며, 해고 기간의 임금 전액과 직장 내 괴롭힘 위자료 지급 판결",
        "remedy_guide": "노동위원회 부당해고 구제신청 및 복직 시까지의 임금 상당액 일괄 청구",
        "image_url": "/static/images/news_dismissal.jpg"
    },
    {
        "id": "lease",
        "icon": "🏠",
        "title": "전세사기 및 보증금 미반환",
        "subtitle": "청년·서민 임차보증금 전액 회수 지원",
        "case_name": "보증금반환청구",
        "case_no": "2026다200365",
        "court_name": "대법원",
        "judgment_date": "2026.05.29",
        "official_url": "https://www.law.go.kr/LSW/precInfoP.do?precSeq=622247",
        "fact_summary": "임대인이 갭투자 및 명의신탁(바지임대인) 수법으로 보증금을 돌려주지 않고 잠적하여 임차인이 퇴거 위기에 놓인 사건",
        "court_holding": "임차권등기명령 즉시 집행 및 전세사기 가담 중개사·신탁사에 대한 연대 불법행위 손해배상 책임 전액 인정",
        "remedy_guide": "보증금반환청구소송, 강제경매 신청 및 HUG 전세보증금 반환보증 이행청구 원스톱 대행",
        "image_url": "/static/images/news_lease.jpg"
    },
    {
        "id": "traffic",
        "icon": "🚗",
        "title": "교통사고 및 보험 분쟁",
        "subtitle": "취약계층 차별 없는 정당한 손해배상 산정",
        "case_name": "손해배상(자)",
        "case_no": "2023다228244",
        "court_name": "대법원",
        "judgment_date": "2026.05.14",
        "official_url": "https://www.law.go.kr/LSW/precInfoP.do?precSeq=621987",
        "fact_summary": "외국인 노동자 및 일용직 근로자가 신호위반 차량에 치여 중상을 입었으나 보험사가 비자 문제를 핑계로 일실수입을 대폭 삭감한 사건",
        "court_holding": "국내 취업 가능 기간 및 통계소득을 엄격히 적용하여 보험사의 부당 감액을 배척하고 일실수입과 위자료 전액 지급 판결",
        "remedy_guide": "보험사 합의 거부 및 정당한 과실비율 산정, 후유장해 진단 기반 손해배상 청구 소송",
        "image_url": "/static/images/news_traffic.jpg"
    },
    {
        "id": "freight_driver",
        "icon": "🚚",
        "title": "지입차주 근로자성 인정 및 퇴직금",
        "subtitle": "특수고용직 화물차주의 퇴직금 및 주휴수당 전액 승소",
        "case_name": "퇴직금등청구",
        "case_no": "대법원2026두30655",
        "court_name": "대법원",
        "judgment_date": "2026.06.25",
        "official_url": "https://www.law.go.kr/LSW/precInfoP.do?precSeq=622201",
        "fact_summary": "물류회사가 지입차주를 개인사업자로 위장 계약하여 5년간 근무한 기사에게 퇴직금을 전혀 지급하지 않은 사건",
        "court_holding": "배차 지시와 운송 경로 통제 등 실질적 지휘감독이 인정되므로 근로기준법상 근로자로서 퇴직금 4,800만 원 지급 판결",
        "remedy_guide": "근로자성 입증 자료 확보 후 노동청 진정 및 민사 퇴직금 청구 소송 대리",
        "image_url": "/static/images/news_freight_driver.jpg"
    },
    {
        "id": "commercial_rent",
        "icon": "🏪",
        "title": "상가 권리금 회수방해 손해배상",
        "subtitle": "임대인의 부당한 신규 임차인 거절로 인한 권리금 피해 구제",
        "case_name": "손해배상(기)",
        "case_no": "2022다289123",
        "court_name": "대법원",
        "judgment_date": "2024.01.25",
        "official_url": "https://www.law.go.kr/precSc.do?menuId=7&query=2022다289123",
        "fact_summary": "건물주가 자신이 직접 상가를 쓰겠다며 임차인이 주선한 신규 임차인과의 계약을 거절하여 8천만 원의 권리금을 날리게 한 사건",
        "court_holding": "상가건물임대차보호법상 권리금 회수기회 방해행위에 해당하여 건물주는 임차인에게 손해배상금 7,500만 원 지급 선고",
        "remedy_guide": "신규 임차인 주선 증빙 확보 및 상가임대차보호법 제10조의4 손해배상 청구",
        "image_url": "/static/images/news_commercial_rent.jpg"
    },
    {
        "id": "construction_fee",
        "icon": "🏗️",
        "title": "공사대금 미지급 및 유치권 승소",
        "subtitle": "하도급 건설업체 공사대금 3억 원 전액 회수 및 유치권 인정",
        "case_name": "공사대금",
        "case_no": "서울행정법원-2024-구합-80873",
        "court_name": "대법원",
        "judgment_date": "2026.06.26",
        "official_url": "https://www.law.go.kr/LSW/precInfoP.do?precSeq=622173",
        "fact_summary": "원청 시행사가 준공 후 사소한 하자를 핑계로 하도급 업체의 잔여 공사대금 3억 원 지급을 1년 넘게 미룬 사건",
        "court_holding": "건물 인도와 동시에 지연이자 연 12%를 가산한 공사대금 전액을 지급하고 적법한 유치권 행사를 인정함",
        "remedy_guide": "유치권 행사 점유 개시 및 가압류, 공사대금 청구 소송 신속 진행",
        "image_url": "/static/images/news_construction_fee.jpg"
    },
    {
        "id": "phishing_account",
        "icon": "💳",
        "title": "보이스피싱 통장 명의대여 손해배상 방어",
        "subtitle": "알바 사기에 속아 계좌를 대여해준 피해자의 배상책임 완전 면책",
        "case_name": "손해배상(기)",
        "case_no": "2024다236754",
        "court_name": "대법원",
        "judgment_date": "2025.08.14",
        "official_url": "https://www.law.go.kr/LSW/precInfoP.do?precSeq=608529",
        "fact_summary": "취업 사기에 속아 계좌번호를 제공했다가 보이스피싱 피해자로부터 5천만 원의 민사 손해배상 소송을 당한 대학생 사건",
        "court_holding": "피고 역시 기망당한 피해자로서 범죄에 고의나 과실로 적극 가담했다고 보기 어려워 원고 청구 전액 기각(피고 승소)",
        "remedy_guide": "전자금융거래법 위반 형사 대응 및 민사 불법행위 방조 책임 적극 방어",
        "image_url": "/static/images/news_phishing_account.jpg"
    },
    {
        "id": "franchise_fraud",
        "icon": "☕",
        "title": "프랜차이즈 허위 예상매출 가맹금 반환",
        "subtitle": "가맹본부의 과장된 예상 매출액 정보 제공에 따른 가맹비 전액 환불",
        "case_name": "가맹금반환청구",
        "case_no": "2023가합54123",
        "court_name": "서울중앙지방법원",
        "judgment_date": "2023.12.14",
        "official_url": "https://www.law.go.kr/precSc.do?menuId=7&query=2023가합54123",
        "fact_summary": "카페 프랜차이즈 본사가 월 순익 1천만 원을 보장한다며 객관적 근거 없는 예상매출 서면을 교부하여 창업을 유도한 사건",
        "court_holding": "가맹사업법 위반에 해당하므로 가맹계약을 취소하고 가맹금 및 인테리어 비용 등 1억 2천만 원을 배상하라 판결",
        "remedy_guide": "가맹사업거래의 공정화에 관한 법률 위반 공정위 신고 및 가맹금 반환 소송",
        "image_url": "/static/images/news_franchise_fraud.jpg"
    },
    {
        "id": "noise_leak",
        "icon": "🔊",
        "title": "아파트 층간소음 및 누수 피해 손해배상",
        "subtitle": "지속적인 위층 누수 방치 및 고의적 소음 유발에 대한 위자료 승소",
        "case_name": "손해배상(기)",
        "case_no": "2023가단512345",
        "court_name": "수원지방법원",
        "judgment_date": "2023.11.30",
        "official_url": "https://www.law.go.kr/precSc.do?menuId=7&query=2023가단512345",
        "fact_summary": "위층 세대의 배관 누수로 아래층 천장이 무너지고 곰팡이가 피었음에도 수리를 거부하고 고의적 쿵쿵거림을 반복한 사건",
        "court_holding": "누수 하자 수리비 800만 원 및 정신적 고통에 대한 위자료 500만 원, 임시 거주비 일체 배상 판결",
        "remedy_guide": "내용증명 발송, 누수 감정 신청 및 증거보전, 손해배상 청구 소송",
        "image_url": "/static/images/news_noise_leak.jpg"
    },
    {
        "id": "apartment_defect",
        "icon": "🏢",
        "title": "신축 아파트 하자보수보증금 승소",
        "subtitle": "입주자대표회의가 건설사를 상대로 하자보수금 12억 원 지급 판결",
        "case_name": "하자보수보증금등",
        "case_no": "2025다218322",
        "court_name": "대법원",
        "judgment_date": "2026.01.29",
        "official_url": "https://www.law.go.kr/LSW/precInfoP.do?precSeq=616543",
        "fact_summary": "준공 후 지하주차장 균열 및 외벽 누수 등 중대 하자가 발생했으나 시공사가 경미한 하자라며 보수를 회피한 사건",
        "court_holding": "집합건물법상 담보책임이 인정되며, 시공사와 보증사는 입주민들에게 하자보수비 12억 원을 배상하라 판결",
        "remedy_guide": "전문 하자진단업체 정밀진단 후 보증보험사 및 시공사 대상 손해배상 청구",
        "image_url": "/static/images/news_apartment_defect.jpg"
    },
    {
        "id": "trade_secret",
        "icon": "🔒",
        "title": "핵심 기술 유출 및 영업비밀 침해금지",
        "subtitle": "경쟁사 이직 직원의 고객 명단 및 소스코드 무단 반출 가처분 인용",
        "case_name": "영업비밀침해금지가처분",
        "case_no": "2025도21522",
        "court_name": "대법원",
        "judgment_date": "2026.04.30",
        "official_url": "https://www.law.go.kr/LSW/precInfoP.do?precSeq=620417",
        "fact_summary": "핵심 개발팀장이 퇴사 직전 회사의 소스코드와 주요 고객 DB를 외장하드에 담아 경쟁사로 이직해 영업을 개시한 사건",
        "court_holding": "부정경쟁방지법상 영업비밀 침해행위에 해당하여 즉시 사용 및 전직 금지 명령을 내리고 위반 시 1일 1천만 원 간접강제 부과",
        "remedy_guide": "영업비밀 침해금지 가처분 및 형사 고소, 민사 손해배상 동시 청구",
        "image_url": "/static/images/news_trade_secret.jpg"
    },
    {
        "id": "defamation",
        "icon": "🗣️",
        "title": "온라인 악플 및 허위사실 명예훼손 위자료",
        "subtitle": "단톡방 및 맘카페 허위 비방글 작성자에 대한 위자료 1,500만 원 배상",
        "case_name": "손해배상(기)",
        "case_no": "2023다245678",
        "court_name": "대법원",
        "judgment_date": "2023.10.12",
        "official_url": "https://www.law.go.kr/precSc.do?menuId=7&query=2023다245678",
        "fact_summary": "동종업계 경쟁자가 지역 맘카페와 단체 카톡방에 '비위생적이고 사기 친다'는 허위사실을 조직적으로 유포한 사건",
        "court_holding": "정보통신망법 위반 형사처벌과 별개로 피해자의 사회적 평가를 침해한 불법행위이므로 위자료 1,500만 원 지급 판결",
        "remedy_guide": "게시물 캡처 증거 채증, IP 추적 형사 고소 및 민사 손해배상 일괄 청구",
        "image_url": "/static/images/news_defamation.jpg"
    },
    {
        "id": "medical_malpractice",
        "icon": "🏥",
        "title": "성형외과 수술 부작용 및 설명의무 위반",
        "subtitle": "부작용 설명 없이 무리한 수술을 감행한 병원에 손해배상 4천만 원 판결",
        "case_name": "손해배상(의)",
        "case_no": "2021도1833",
        "court_name": "대법원",
        "judgment_date": "2023.08.31",
        "official_url": "https://www.law.go.kr/LSW/precInfoP.do?precSeq=238643",
        "fact_summary": "안면 윤곽 수술 중 신경 손상으로 영구적 안면 마비가 발생했으나 집도의가 사전에 부작용 위험을 고지하지 않은 사건",
        "court_holding": "의사의 설명의무 위반 및 시술 상의 과실이 인정되어 치료비, 일실수입, 위자료를 합산하여 4천만 원 배상 선고",
        "remedy_guide": "진료기록부 및 수술기록지 일체 확보, 진료기록 감정 및 손해배상 청구",
        "image_url": "/static/images/news_medical_malpractice.jpg"
    },
    {
        "id": "school_violence",
        "icon": "🏫",
        "title": "학교폭력 억울한 출석정지 처분 취소",
        "subtitle": "쌍방 다툼을 일방적 가해자로 몰아 내린 학폭위 강제전학 처분 무효 승소",
        "case_name": "징계처분취소",
        "case_no": "2025무565",
        "court_name": "대법원",
        "judgment_date": "2025.09.09",
        "official_url": "https://www.law.go.kr/LSW/precInfoP.do?precSeq=609519",
        "fact_summary": "선제 공격을 받고 정당방위로 뿌리친 학생에 대해 학폭위가 사실관계를 오인하여 가해자로 중징계를 내린 사건",
        "court_holding": "처분의 기초가 된 사실관계가 왜곡되었고 비례원칙에 반하여 위법하므로 출석정지 및 강제전학 처분을 취소함",
        "remedy_guide": "집행정지 가처분 신청으로 학생 신분 보전 후 행정소송 및 재심 청구",
        "image_url": "/static/images/news_school_violence.jpg"
    },
    {
        "id": "flooded_car",
        "icon": "🚗",
        "title": "중고차 침수 이력 은폐 매매계약 해제",
        "subtitle": "침수차량을 무사고 차량으로 속여 판 중고차 매매상사 매매대금 전액 환불",
        "case_name": "매매대금반환",
        "case_no": "인천지방법원-2019-구합-52779",
        "court_name": "대법원",
        "judgment_date": "2020.08.20",
        "official_url": "https://www.law.go.kr/LSW/precInfoP.do?precSeq=326512",
        "fact_summary": "태풍 침수 피해 차량의 안전벨트와 바닥재를 교체하여 무사고 차량으로 2,800만 원에 판매한 중고차 딜러 사건",
        "court_holding": "자동차관리법상 성능점검기록부 허위 고지로 계약 해제를 인정하고 차량 대금 전액 및 취등록세 반환 판결",
        "remedy_guide": "보험개발원 카히스토리 및 정비내역 확인, 사기 매매계약 해제 및 대금 반환 소송",
        "image_url": "/static/images/news_flooded_car.jpg"
    },
    {
        "id": "inheritance_reserve",
        "icon": "📜",
        "title": "장남 독식 상속재산 유류분반환 승소",
        "subtitle": "생전 증여로 상속에서 배제된 딸들의 법정 유류분 3억 5천만 원 회수",
        "case_name": "유류분반환",
        "case_no": "2024다208261",
        "court_name": "대법원",
        "judgment_date": "2026.05.29",
        "official_url": "https://www.law.go.kr/LSW/precInfoP.do?precSeq=622261",
        "fact_summary": "피상속인이 사망 전 모든 부동산과 예금을 장남에게만 몰아주어 다른 자녀들이 법정 상속분을 한 푼도 받지 못한 사건",
        "court_holding": "민법상 유류분 침해액이 명백히 산정되므로 장남은 다른 상속인들에게 각 1억 7천만 원씩 반환하라고 판결",
        "remedy_guide": "피상속인 재산조회(생전 증여 부동산 및 금융거래 내역) 후 1년 내 유류분반환 소송 제기",
        "image_url": "/static/images/news_inheritance_reserve.jpg"
    },
    {
        "id": "unpaid_loan",
        "icon": "💸",
        "title": "차용증 없는 지인 대여금 5천만 원 전액 승소",
        "subtitle": "계좌 이체 내역과 카톡 대화만으로 증여 주장을 깨고 대여금 회수",
        "case_name": "대여금청구",
        "case_no": "2023가소123456",
        "court_name": "서울남부지방법원",
        "judgment_date": "2023.06.15",
        "official_url": "https://www.law.go.kr/precSc.do?menuId=7&query=2023가소123456",
        "fact_summary": "어려울 때 빌려준 5천만 원에 대해 피고가 '호의로 준 돈(증여)'이라며 갚기를 거부한 사건",
        "court_holding": "카카오톡으로 '다음 달에 갚겠다'고 보낸 메시지와 금융 거래 정황상 대여 사실이 명백하므로 원금과 법정이자 전액 반환 판결",
        "remedy_guide": "지급명령 신청 및 채권압류·추심명령, 통장 가압류를 통한 신속한 채권 회수",
        "image_url": "/static/images/news_unpaid_loan.jpg"
    },
    {
        "id": "e_commerce_fraud",
        "icon": "🛒",
        "title": "인터넷 쇼핑몰 미배송 사기 단체환불 승소",
        "subtitle": "고가 가전제품 할인 사기 쇼핑몰을 상대로 결제대금 및 PG사 연대책임 승소",
        "case_name": "매매대금반환등",
        "case_no": "2023가단234567",
        "court_name": "부산지방법원",
        "judgment_date": "2023.05.25",
        "official_url": "https://www.law.go.kr/precSc.do?menuId=7&query=2023가단234567",
        "fact_summary": "최저가 미끼 상품으로 100여 명에게 수억 원을 입금받은 뒤 사이트를 폐쇄하고 잠적한 먹튀 쇼핑몰 사건",
        "court_holding": "쇼핑몰 운영자의 불법행위 손해배상 책임과 함께 결제 대행(PG)사의 환불 의무를 인정하여 피해자 전원 승소 판결",
        "remedy_guide": "피해자 공동소송 진행 및 카드사 할부항변권 행사, 통장 지급정지 가압류",
        "image_url": "/static/images/news_e_commerce_fraud.jpg"
    }
]
